export const kenyanCounties: string[] = [
  "Baringo",
  "Bomet",
  "Bungoma",
  "Busia",
  "Elgeyo-Marakwet",
  "Embu",
  "Garissa",
  "Homa Bay",
  "Isiolo",
  "Kajiado",
  "Kakamega",
  "Kericho",
  "Kiambu",
  "Kilifi",
  "Kirinyaga",
  "Kisii",
  "Kisumu",
  "Kitui",
  "Kwale",
  "Laikipia",
  "Lamu",
  "Machakos",
  "Makueni",
  "Mandera",
  "Marsabit",
  "Meru",
  "Migori",
  "Mombasa",
  "Murang'a",
  "Nairobi",
  "Nakuru",
  "Nandi",
  "Narok",
  "Nyamira",
  "Nyandarua",
  "Nyeri",
  "Samburu",
  "Siaya",
  "Taita-Taveta",
  "Tana River",
  "Tharaka-Nithi",
  "Trans Nzoia",
  "Turkana",
  "Uasin Gishu",
  "Vihiga",
  "Wajir",
  "West Pokot",
];

export const houseAmenities: string[] = [
  "Wifi",
  "Water",
  "Parking",
  "Drawers",
  "Sinks",
  "wardrobe",
  "Electricity",
  " Furnishing",
  "Security",
  "Air Conditioning",
  "Heating",
  "Swimming Pool",
  "Gym",
  "Parking Space",
  "Balcony",
  "Fireplace",
  "Garden",
  "Pet-Friendly",
  "Furnished",
  "Unfurnished",
  "Laundry Facilities",
  "Dishwasher",
  "Elevator",
  "Wheelchair Accessible",
  "Smart Home Features",
  "Cable TV",
  "Outdoor Space",
  "BBQ Area",
  "Playground",
  "Community Center",
  "Storage Space",
  "Waterfront",
  "Scenic View",
  "Near Public Transportation",
  "Close to Schools",
  "Close to Shopping",
  "Close to Parks",
  "Close to Restaurants",
  "Security Guard",
];

export const typesOfProperties = [
  "Bedsitter",
  "Single Room",
  "Double Room",
  "1 Bedroom",
  "2 Bedroom",
  "3 Bedroom",
  "4+ Bedroom",
  "Apartments",
  "House",
  "Hostel",
  "Office space",
  "Shop space",
];
